pipeline {
    agent { label 'linux-agent' }
    parameters {
        choice(name: 'Environment', choices: ['Development', 'Production'], description: 'Choose an environment where deploy the Database')
    }
    environment {
        DEPLOY_TO = "${params.Environment}"
    }
    stages {
        stage ('Deploy to Development') {
            when {

            }
            steps {
                echo "Environment: ${DEPLOY_TO}"
            }
        }

        stage ('Deploy to Production') {
            when {

            }
            steps {
                echo "Environment: ${DEPLOY_TO}"
            }
        }
    }
}